[package]
name = "esp-openthread"
version = "0.4.0"
edition = "2021"

[dependencies]
esp-openthread-sys = { path = "../esp-openthread-sys" }
esp-hal = {version= "0.20.1", git = "https://github.com/esp-rs/esp-hal.git", rev="c0a9934"}
esp-hal-procmacros = {version= "0.13.0", git = "https://github.com/esp-rs/esp-hal.git", features=["interrupt"], rev="c0a9934"}
esp-ieee802154 = {version= "0.2.0", git = "https://github.com/esp-rs/esp-hal.git", rev="c0a9934"}
log = "0.4.21"
critical-section = "1.1.1"
fugit = "0.3.7"
bitflags = "2.5.0"
heapless = "0.8.0"
no-std-net = "0.6.0"
rtt-target = {version ="0.5.0", optional=true}



[features]
esp32c6 = [ "esp-ieee802154/esp32c6", "esp-hal/esp32c6"]
esp32h2 = [ "esp-ieee802154/esp32h2", "esp-hal/esp32h2"]
srp-client = []
debug-target=["dep:rtt-target"]